#!/bin/bash
#
# A tiny script to check what protos are allowed
# against a given server at host:port
#

if [ $# -ne 2 ]; then
  echo "usage:"
  echo "test_protos <host> <port>"
  exit 1
fi

host=$1
port=$2

for proto in ssl3 tls1 tls1_1 tls1_2; do
  echo "trying $proto"
  out=$(echo "Q" | openssl s_client -connect $host:$port -$proto 2>&1)

  if [[ $out =~ "Cipher is (NONE)" ]]; then
    echo "info: proto $proto failed"
    continue
  fi 

  echo "info: proto $proto worked"
done
